### ISSUE TITLE
Ground truth values for velocity of vehicles ?

### ISSUE THREAD

**Issue by PH2021009** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#12]
Thanks for sharing the radar raw data.
Can you please share each data set's ground truth velocity values in text labels?
I saw that text labels only contain px,py,width,length data.
please let me know if thats possible to share.

**Comment by Xiangyu-Gao** [comment]
unfortunately, we do not have the gt label for velocity. Sorry for the inconvenience,
