### ISSUE TITLE
The file id between radar, image and label do not match.

### ISSUE THREAD

**Issue by SlytherinGe** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#2]
For example in the 2019_04_09_cms1000 folder, the radar data starts from 000002.mat, but the image and label start from 0000000000.jpg/.csv. Also 0000000000.csv is empty with no data.
Please check your uploaded data. I downloaded them from the google drive.

**Comment by Xiangyu-Gao** [comment]
Thanks for posting this issue. The radar, camera image, and label are matched via their id. For example, 000002.mat is matched to 0000000002.jpg and 0000000002.csv. For the extra images and labels, please simply ignore them.
