### ISSUE TITLE
Unmatched labels in raw label files

### ISSUE THREAD

**Issue by kathy-lee** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#7]
Hi @Xiangyu-Gao , thank you for sharing this great dataset with us! I just have one question related to the annotations: After checking all the label files, I find there is no class id '5' existed in all .csv label files but there are two seq contain class id '1' : `2019_05_09_mlms003` and `2019_05_09_bm1s007`:
2019_05_09_bm1s007 contains class_ids '1' at:
0000000629.csv
0000000634.csv
0000000635.csv
0000000636.csv
0000000637.csv
0000000639.csv
2019_05_09_mlms003 contains class_ids '1' at:
0000000607.csv
0000000607.csv
0000000625.csv
0000000645.csv
0000000773.csv
0000000845.csv
0000000608.csv
0000000609.csv
0000000610.csv
0000000611.csv
0000000612.csv
0000000613.csv
0000000615.csv
0000000616.csv
0000000617.csv
0000000618.csv
0000000619.csv
0000000620.csv
0000000621.csv
0000000622.csv
0000000623.csv
0000000624.csv
0000000591.csv
0000000592.csv
0000000593.csv
0000000594.csv
0000000595.csv
0000000596.csv
0000000597.csv
0000000599.csv
0000000600.csv
0000000601.csv
0000000602.csv
0000000603.csv
0000000604.csv
0000000605.csv
0000000606.csv
0000000626.csv
0000000627.csv
0000000628.csv
0000000629.csv
0000000630.csv
0000000631.csv
0000000632.csv
0000000633.csv
0000000634.csv
0000000635.csv
0000000636.csv
0000000637.csv
0000000638.csv
0000000639.csv
0000000640.csv
0000000641.csv
0000000642.csv
0000000643.csv
0000000644.csv
0000000846.csv
0000000847.csv
0000000829.csv
0000000830.csv
0000000831.csv
0000000832.csv
0000000833.csv
0000000834.csv
0000000835.csv
0000000836.csv
0000000837.csv
0000000838.csv
0000000839.csv
0000000840.csv
0000000841.csv
0000000842.csv
0000000843.csv
0000000844.csv
0000000792.csv
0000000774.csv
0000000775.csv
0000000776.csv
0000000777.csv
0000000778.csv
0000000779.csv
0000000780.csv
0000000781.csv
0000000782.csv
0000000783.csv
0000000784.csv
0000000759.csv
0000000760.csv
0000000761.csv
0000000762.csv
0000000763.csv
0000000764.csv
0000000765.csv
0000000766.csv
0000000767.csv
0000000768.csv
0000000769.csv
0000000770.csv
0000000771.csv
0000000772.csv
Is there anything wrong with the label map ? (in the repo: label_map = {0: 'person',
              2: 'car',
              3: 'motorbike',
              5: 'bus',
              7: 'truck',
              80: 'cyclist',
              })

**Comment by Xiangyu-Gao** [comment]
Thank you for your questions. The label map is correct. 1) You may discard the number 1 labeling. It should be the redundant noise label. 2)  The shared datasets should have few or no data of bus (label 5). We do have use the label map for label our complete dateset.  To make the label map consistent between the shared datasets and ours and enable more data release in future, we keep the bus class in the label map.

**Comment by kathy-lee** [comment]
Thank you for your answer, it's very helpful!
