### ISSUE TITLE
Radar data and camera data time alignment

### ISSUE THREAD

**Issue by yyuan-luo** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#8]
Hi Xiangyu,

I have a question about synchronising the radar and camera data. As far as I know, the TI mmWave Studio does not label any timestamps to the data, not even for the first frame. I am just wondering how you solved this issue, by using SW/HW trigger? Thanks in advance.

**Comment by Xiangyu-Gao** [comment]
We use a SW trigger but I remembered that the TI device has the option of a HW trigger, you may want to explore that.
