### ISSUE TITLE
Regarding the radar configuration

### ISSUE THREAD

**Issue by yyuan-luo** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#9]
Hi Xiangyu,

I have some questions regarding the radar configuration. I tried to set my own AWR1843 radar to the same configuration you used. However, I had some problems when doing this.

### My radar configuration
<img width="1206" alt="Screenshot 2023-12-05 203820" src="https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/52521413/069c3ad1-3220-4891-8050-7dbb55657baa">
<img width="1218" alt="Screenshot 2023-12-05 203757" src="https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/52521413/9292702b-f045-4b98-bedf-3dd9384799f0">
<img width="1226" alt="Screenshot 2023-12-05 203747" src="https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/52521413/75b69b64-dc7e-4893-8238-13f32dd631f8">

#### Tx1 with Tx2 or Tx1 with Tx3?
There are in total 3 Tx on AWR1843. In your project, you applied TDM on the Tx on the left and the one on the right. Between them, the distance is `4d`. However, in mmWave Studio, I am not sure what is the correlation between the 3 Tx in the mmWave Studio and the 3 Tx actually on the radar board. It would be very nice if you could point it out to me.

#### The frame periodicity
```
radar_configs = {
    "startFreqConst_GHz": 77.0,
    "bandwidth_GHz": 0.67,
    "chirpDuration_usec": 60.0,     # single chirp per antenna
    "freqSlopeConst_MHz_usec": 21.0,  # slope: MHz/us
    "numAdcSamples": 128,   # samples
    "digOutSampleRate": 4000.0,     # sampling rate: Ksps
    "numLoops": 255,     # chirp loops
    "framePeriodicity_msec": 33.33333,  # frame rate 30 fps
}
```
In your configuration, the frame periodicity is `33.3333ms`. I tried to use the same configuration except the `chirpDuraiton_usec` which I don't know how to set. In the end, the mmWave Studio reminds me that the minimum requirement for frame periodicity is `81.6`ms. Could you please go through my configuration as provided above to provide some possible explanation for this?

**Thanks in advance!**

**Comment by yyuan-luo** [comment]
By playing the `idle time` and `Ramp End Time`, I can set the frame periodicity to `33.3333` ms. However, the generated RA and RD maps do not show any peak values, which do not align with the post-processing results from mmWave Studio, shown bellow.
![ra](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/52521413/03d93a61-c920-4068-9aaf-eaf4cb89c653)
![rd](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/52521413/2529a9d6-855c-46eb-be43-a6ce17570d28)

The setting for the above results is `idle time = 10 us` and `Ramp End Time = 50 us`. So that the minimum `frame periodicity = (10 + 50) * 2 * 255 = 30.6 ms`.

Could you please help to spot what is going wrong, or could you please provide your setting to the `idle time` and `Ramp End Time`? Thanks.

**Comment by yyuan-luo** [comment]
I think I have calculated both time based on the `bandWidth` and `chirpDuration`.

**Comment by Xiangyu-Gao** [comment]
**Tx1 with Tx2 or Tx1 with Tx3?**
I do not remember the details since it has been a long time ago. You may want to refer to the TI reference doc for checking the name correspondence.
**The frame periodicity**
The `Ramp End Time` should be longer than the exact value, 32.66us,  you calculated to leave some room. The `idle time` can be very small

**Comment by yyuan-luo** [comment]
Thanks for the reply. Now, I get it. The `bandwidth` here refers actually to the frequency change in `ADC sampling Time`. Based on your configuration, `ADC sampling time = 128 / 400k= 32us`, hence the `bandwidth = 32 x 21Mhz / 1000 = 0.67GHz`. I thought that the `bandwidth` means the value showed in mmWave Studio, which equals `slope x ramp end time`. Now, it it clear.
